name: pets
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  get: ^4.6.6

  image_picker: ^1.0.4

  google_fonts: ^6.1.0

  feather_icons: ^1.2.0

  http: ^1.1.0

  webview_flutter: ^4.4.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - images/afif.png
  - images/cat.png
